# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Add_elements_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_Element(object):
    def setupUi(self, Add_Element):
        Add_Element.setObjectName("Add_Element")
        Add_Element.setWindowModality(QtCore.Qt.ApplicationModal)
        Add_Element.resize(263, 170)
        Add_Element.setMinimumSize(QtCore.QSize(263, 170))
        Add_Element.setMaximumSize(QtCore.QSize(263, 170))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Add_Element.setWindowIcon(icon)
        Add_Element.setModal(True)
        self.formLayoutWidget = QtWidgets.QWidget(Add_Element)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 241, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(1)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Add_Element)
        self.buttonBox.setGeometry(QtCore.QRect(10, 120, 241, 28))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Add_Element)
        QtCore.QMetaObject.connectSlotsByName(Add_Element)

    def retranslateUi(self, Add_Element):
        _translate = QtCore.QCoreApplication.translate
        Add_Element.setWindowTitle(_translate("Add_Element", "Добавить элемент"))
        self.label.setText(_translate("Add_Element", "Ref Des"))
        self.label_2.setText(_translate("Add_Element", "Группа"))
        self.label_3.setText(_translate("Add_Element", "Элемент"))
import Resourses_rc
