# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cases_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cases(object):
    def setupUi(self, Cases):
        Cases.setObjectName("Cases")
        Cases.setWindowModality(QtCore.Qt.ApplicationModal)
        Cases.resize(388, 468)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Cases.setWindowIcon(icon)
        Cases.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Cases)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(Cases)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 0, 1, 1)
        self.close_btn = QtWidgets.QPushButton(Cases)
        self.close_btn.setObjectName("close_btn")
        self.gridLayout.addWidget(self.close_btn, 2, 3, 1, 1)
        self.comboBox = QtWidgets.QComboBox(Cases)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 3)
        self.del_btn = QtWidgets.QPushButton(Cases)
        self.del_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.del_btn.setIcon(icon1)
        self.del_btn.setObjectName("del_btn")
        self.gridLayout.addWidget(self.del_btn, 2, 2, 1, 1)
        self.add_btn = QtWidgets.QPushButton(Cases)
        self.add_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_btn.setIcon(icon2)
        self.add_btn.setObjectName("add_btn")
        self.gridLayout.addWidget(self.add_btn, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(Cases)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(Cases)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Cases)
        QtCore.QMetaObject.connectSlotsByName(Cases)

    def retranslateUi(self, Cases):
        _translate = QtCore.QCoreApplication.translate
        Cases.setWindowTitle(_translate("Cases", "Список корпусов"))
        self.close_btn.setText(_translate("Cases", "Закрыть"))
        self.label.setText(_translate("Cases", "Группа:"))
import Resourses_rc
