# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Change_elements_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Change_Element(object):
    def setupUi(self, Change_Element):
        Change_Element.setObjectName("Change_Element")
        Change_Element.setWindowModality(QtCore.Qt.ApplicationModal)
        Change_Element.resize(262, 140)
        Change_Element.setMinimumSize(QtCore.QSize(262, 140))
        Change_Element.setMaximumSize(QtCore.QSize(262, 140))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Change_Element.setWindowIcon(icon)
        Change_Element.setModal(True)
        self.formLayoutWidget = QtWidgets.QWidget(Change_Element)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 241, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(1)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.ref_box = QtWidgets.QComboBox(self.formLayoutWidget)
        self.ref_box.setObjectName("ref_box")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ref_box)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Change_Element)
        self.buttonBox.setGeometry(QtCore.QRect(10, 100, 241, 28))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Change_Element)
        QtCore.QMetaObject.connectSlotsByName(Change_Element)

    def retranslateUi(self, Change_Element):
        _translate = QtCore.QCoreApplication.translate
        Change_Element.setWindowTitle(_translate("Change_Element", "Изменить элемент"))
        self.label.setText(_translate("Change_Element", "Ref Des"))
        self.label_2.setText(_translate("Change_Element", "Группа"))
        self.label_3.setText(_translate("Change_Element", "Элемент"))
import Resourses_rc
