# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Projects_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Projects(object):
    def setupUi(self, Projects):
        Projects.setObjectName("Projects")
        Projects.setWindowModality(QtCore.Qt.ApplicationModal)
        Projects.resize(440, 562)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Projects.setWindowIcon(icon)
        Projects.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Projects)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.close_btn = QtWidgets.QPushButton(Projects)
        self.close_btn.setObjectName("close_btn")
        self.gridLayout.addWidget(self.close_btn, 1, 3, 1, 1)
        self.add_btn = QtWidgets.QPushButton(Projects)
        self.add_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_btn.setIcon(icon1)
        self.add_btn.setObjectName("add_btn")
        self.gridLayout.addWidget(self.add_btn, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Projects)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.del_btn = QtWidgets.QPushButton(Projects)
        self.del_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.del_btn.setIcon(icon2)
        self.del_btn.setObjectName("del_btn")
        self.gridLayout.addWidget(self.del_btn, 1, 2, 1, 1)
        self.tableView = QtWidgets.QTableView(Projects)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Projects)
        QtCore.QMetaObject.connectSlotsByName(Projects)

    def retranslateUi(self, Projects):
        _translate = QtCore.QCoreApplication.translate
        Projects.setWindowTitle(_translate("Projects", "Список проектов"))
        self.close_btn.setText(_translate("Projects", "Закрыть"))
import Resourses_rc
